version: "2.0"

services: 
    legalfishing:
        image: legal-fishing
        container_name: knowledge-proof
        volumes: 
#             - /tmp/flureeConfig.json:./flureeConfig.json
            - /var/zeeve-app:/usr/src/legal/build
        expose: 
            - 3000
        ports: 
            - "3000:3000"
        command: |
            bash -c "npm run build && npm start && node deploy.js"
        network_mode: host
